README.md, examples/simple_app.rs, src/api/config.rs, src/api/error.rs, src/api/mod.rs, src/api/props.rs, src/common/remote/conn.rs, src/common/remote/remote_client.rs, src/common/remote/request/client_request.rs, src/config/mod.rs, src/config/server_response.rs, src/config/worker.rs, src/lib.rs
- Doc for Nacos sdk Rust.
- std config api.
=> Feat: doc and std config api.

src/common/remote/request/client_request.rs, src/common/remote/request/server_request.rs, src/common/remote/response/server_response.rs, src/config/server_response.rs, src/config/worker.rs, src/lib.rs
- refactor: adjust worker lock logic
- chore: governance dead code.
=> Refactor code optimization.

src/common/remote/conn.rs, src/config/worker.rs
=> Log: add more conn log.

nacos-macro/src/lib.rs, src/common/executor/mod.rs, src/naming/error/mod.rs, src/naming/grpc/client_abilities.rs, src/naming/grpc/grpc_service.rs, src/naming/grpc/handler/default_handler.rs, src/naming/grpc/handler/mod.rs, src/naming/grpc/message/mod.rs, src/naming/grpc/message/request/instance_request.rs, src/naming/grpc/message/request/mod.rs, src/naming/grpc/message/request/server_check_request.rs, src/naming/grpc/message/request/set_up_request.rs, src/naming/grpc/message/response/error_response.rs, src/naming/grpc/message/response/instance_response.rs, src/naming/grpc/message/response/mod.rs, src/naming/grpc/message/response/server_check_response.rs, src/naming/grpc/mod.rs, src/naming/mod.rs
relate #2 
- 增加 相关错误 抽象 NacosError
- 增加 bi 事件处理器注册逻辑
- 完成服务注册
=> feat: 完成 check-server 交互

nacos-macro/src/request.rs, nacos-macro/src/response.rs, src/api/error.rs, src/api/naming.rs, src/api/props.rs, src/naming/grpc/client_abilities.rs, src/naming/grpc/grpc_service.rs, src/naming/grpc/message/mod.rs, src/naming/grpc/message/request/instance_request.rs, src/naming/grpc/message/request/set_up_request.rs, src/naming/mod.rs
- 完成服务下线功能
- 优化request宏和response宏
- 增加 GrpcMessageRequest 和 GrpcMessageResponse 特征
- 增加服务注册失败错误和取消注册失败错误
- client_props 增加 client_version 字段
- GrpcMessageBody 重命名 GrpcMessageData
rate #2
=> feat: 服务下线

nacos-macro/src/lib.rs, nacos-macro/src/request.rs, src/api/error.rs, src/api/naming.rs, src/naming/grpc/message/mod.rs, src/naming/grpc/message/request/batch_instance_request.rs, src/naming/grpc/message/request/instance_request.rs, src/naming/grpc/message/request/mod.rs, src/naming/grpc/message/request/server_check_request.rs, src/naming/grpc/message/request/set_up_request.rs, src/naming/grpc/message/response/batch_instance_response.rs, src/naming/grpc/message/response/error_response.rs, src/naming/grpc/message/response/instance_response.rs, src/naming/grpc/message/response/mod.rs, src/naming/grpc/message/response/server_check_response.rs, src/naming/mod.rs
- 宏增加 module 参数
- request 宏增加 namespace,serviceName,groupName 字段
- 完成批量注册功能
relate #2
=> feat: 批量注册

nacos-macro/src/lib.rs, src/api/error.rs, src/api/naming.rs, src/naming/grpc/grpc_service.rs, src/naming/grpc/message/request/mod.rs, src/naming/grpc/message/request/server_check_request.rs, src/naming/grpc/message/request/service_query_request.rs, src/naming/grpc/message/request/set_up_request.rs, src/naming/grpc/message/response/mod.rs, src/naming/grpc/message/response/query_service_response.rs, src/naming/grpc/message/response/server_check_response.rs, src/naming/mod.rs
- 宏新增 internal 属性
- 新增服务查询相关 error
- ServiceInstance 中的 cluster_name 使用 option包裹
- AsyncFuture 增加范型
- 优化异步相关逻辑,简化代码
- 移除 tenant 概念使用 namespace 替代
relate #2
=> feat: 服务查询

Cargo.toml, src/api/error.rs, src/api/naming.rs, src/naming/chooser/mod.rs, src/naming/grpc/message/request/mod.rs, src/naming/grpc/message/request/service_list_request.rs, src/naming/grpc/message/response/mod.rs, src/naming/grpc/message/response/service_list_response.rs, src/naming/mod.rs
- 服务选取
- service list
relate #2
=> feat: 服务选取

src/config/worker.rs
- test_client_worker_add_listener
- test_client_worker_add_listener_then_remove
- test_cache_data_add_listener
- test_cache_data_add_listener_then_remove
=> test(config-worker): test client_worker add cache_datda

src/config/worker.rs
- ConfigChangeListener 在独立的线程力触发通知逻辑。
=> feat(config-listener): ConfigChangeListener Notify in independent thread.

src/api/config.rs, src/config/mod.rs
=> feat(config-api #29): remove_listener() for Remove a Listener.

src/api/config.rs, src/common/remote/request/mod.rs, src/common/remote/response/mod.rs, src/config/client_request.rs, src/config/mod.rs, src/config/server_response.rs, src/config/worker.rs
=> feat(config-api #29): remove_config() for Remove a Config.

src/api/config.rs, src/api/mod.rs, src/api/plugin/config_filter.rs, src/api/plugin/encryption.rs, src/api/plugin/mod.rs, src/common/remote/conn.rs, src/config/cache.rs, src/config/mod.rs, src/config/server_response.rs, src/config/util.rs, src/config/worker.rs
=> feat(api-plugin #17): ConfigFilter and EncryptionPlugin

src/api/naming.rs, src/naming/grpc/grpc_client.rs, src/naming/grpc/grpc_service.rs, src/naming/mod.rs
=> enhance: remove panic when the target server connot connect

src/config/worker.rs
=> [ISSUES #49] fix config listener cannot listen config data change

examples/simple_app.rs, src/api/constants.rs, src/common/remote/grpc/grpc_client.rs, src/common/remote/grpc/mod.rs, src/config/worker.rs
- add naming simple
- optimize config logic
- add use_local_subchannel_pool(true)
=> refactor: optimize config logic, add use_local_subchannel_pool(true), add naming simple.

README.md, examples/simple_app.rs, src/api/config.rs, src/api/constants.rs, src/api/props.rs, src/common/remote/grpc/grpc_client.rs, src/common/remote/grpc/mod.rs, src/common/remote/mod.rs, src/lib.rs, src/naming/mod.rs
=> Change: server-addr 默认 0.0.0.0:8848，grpc 链接端口+1000

examples/simple_app.rs, src/api/events/mod.rs, src/api/naming.rs, src/common/event_bus/mod.rs, src/common/remote/grpc/grpc_client.rs, src/common/remote/grpc/handler/client_detection_request_handler.rs, src/common/remote/grpc/handler/mod.rs, src/common/remote/grpc/message/request/client_detection_request.rs, src/common/remote/grpc/message/request/mod.rs, src/common/remote/grpc/message/response/client_detection_response.rs, src/common/remote/grpc/message/response/mod.rs, src/common/remote/grpc/mod.rs, src/config/worker.rs, src/naming/cache/mod.rs, src/naming/handler/naming_push_request_handler.rs, src/naming/mod.rs
- enhance event bus
- enhance grpc handler
- add ClientDetectionRequestHandler
- enhance healthy check logic
Close #55
=> [ISSUES #55] enhance grpc client reconnect logic

Cargo.toml, nacos-macro/src/request.rs, src/api/config.rs, src/api/naming.rs, src/api/plugin/auth/auth_by_http.rs, src/api/plugin/auth/mod.rs, src/api/plugin/mod.rs, src/api/props.rs, src/common/remote/grpc/message/mod.rs, src/config/mod.rs, src/config/worker.rs, src/naming/mod.rs
=> [ISSUE #18] Feature: Auth 鉴权；账密登陆 accessToken

src/api/config.rs, src/api/naming.rs, src/common/remote/grpc/bi_channel.rs, src/common/remote/grpc/events/grpc_connection_health_check_event.rs, src/common/remote/grpc/grpc_client.rs, src/common/remote/grpc/handler/client_detection_request_handler.rs, src/common/remote/grpc/handler/default_handler.rs, src/common/remote/grpc/handler/mod.rs, src/common/remote/grpc/message/mod.rs, src/common/remote/grpc/mod.rs, src/config/handler.rs, src/naming/handler/naming_push_request_handler.rs, src/naming/mod.rs
- enhance bi channel logic
- enhance grpc client reconnect logic
Close #53
=> [ISSUES #53] enhance grpc healthy check

src/common/remote/grpc/mod.rs, src/naming/mod.rs, src/naming/redo/automatic_request/batch_instance_request.rs, src/naming/redo/automatic_request/instance_request.rs, src/naming/redo/automatic_request/subscribe_service_request.rs, src/naming/redo/mod.rs, src/naming/subscribers/mod.rs
=> [ISSUES #63] add auth plugin for automatic request

src/api/events/naming/instances_change_event.rs, src/common/remote/grpc/message/mod.rs, src/naming/dto/mod.rs, src/naming/handler/naming_push_request_handler.rs, src/naming/mod.rs
=> [ISSUES #67] naming service push

src/api/error.rs, src/common/remote/grpc/mod.rs, src/naming/handler/naming_push_request_handler.rs, src/naming/mod.rs, src/naming/subscribers/instances_change_event_subscriber.rs
- enhance api error enum
- grpc client  delay  init
Close #75
=> [ISSUES #75] fix empty group name register service

src/api/plugin/auth/auth_by_http.rs, src/api/props.rs, src/common/remote/grpc/grpc_client.rs, src/common/remote/mod.rs, src/config/worker.rs, src/naming/mod.rs
=> refactor(issue #79): AuthPlugin support multi server-addr

CHANGELOG.md, Cargo.toml
- 支持设置多服务端地址，形如：`address:port[,address:port],...]`
---
- Support multi server-addr, following format: `address:port[,address:port],...]`
=> chore: upgrade version to 0.2.1

src/api/naming.rs
=> [ISSUES #82] fix cluster name is invalid

src/api/naming.rs, src/naming/mod.rs
=> [ISSUES #100] Change: naming api register_instance/select_instances

README.md
=> doc: link to nacos-sdk-rust-binding-node

src/naming/handler/naming_push_request_handler.rs
=> [ISSUES #102] fix naming changed service log

src/common/remote/grpc/grpc_client.rs
=> [ISSUES #101]  env cq count decrease to 1

Cargo.toml, src/api/config.rs, src/api/naming.rs, src/config/mod.rs, src/config/worker.rs, src/naming/mod.rs
=> [ISSUES #107] Add asynchronous api

Cargo.toml, README.md, examples/simple_app.rs, src/api/plugin/auth/auth_by_http.rs
- login with url encode username password.
=> chore: login with url encode username password.

src/naming/handler/naming_push_request_handler.rs
=> [ISSUES #116] fix service info push many times from server

src/common/remote/grpc/events/client_init_complete_event.rs, src/common/remote/grpc/events/connection_health_check_event.rs, src/common/remote/grpc/events/disconnect_event.rs, src/common/remote/grpc/events/mod.rs, src/common/remote/grpc/events/reconnected_event.rs, src/common/remote/grpc/events/shutdown_event.rs, src/common/remote/grpc/grpc_client.rs, src/common/remote/grpc/mod.rs, src/common/remote/grpc/subscribers/connection_health_check_subscriber.rs, src/common/remote/grpc/subscribers/mod.rs, src/common/remote/grpc/subscribers/reconnected_subscriber.rs, src/naming/redo/mod.rs, src/naming/subscribers/redo_task_disconnect_event_subscriber.rs, src/naming/subscribers/redo_task_reconnect_event_subscriber.rs
- set keep alive to 30s
Close #113
=> [ISSUES #113] set keep alive to 30s

Cargo.toml, examples/simple_app.rs, src/api/plugin/auth/auth_by_http.rs, src/api/plugin/auth/mod.rs, src/api/props.rs, src/common/remote/grpc/grpc_client.rs, src/common/remote/grpc/mod.rs, src/common/remote/mod.rs, src/config/worker.rs, src/naming/mod.rs
1. 新增自定义grpc port支持;
2. 新增tls特性, 当前暂时支持 https 认证
FIX:  #120
=> add https scheme in feathre for auth and custom grpc port support

src/api/plugin/auth/auth_by_http.rs, src/common/event_bus/mod.rs, src/common/executor/mod.rs, src/common/remote/grpc/bi_channel.rs, src/common/remote/grpc/grpc_client.rs, src/common/remote/grpc/handler/client_detection_request_handler.rs, src/common/remote/grpc/handler/default_handler.rs, src/common/remote/grpc/mod.rs, src/common/remote/grpc/subscribers/connection_health_check_subscriber.rs, src/common/remote/grpc/subscribers/reconnected_subscriber.rs, src/config/handler.rs, src/config/worker.rs, src/naming/chooser/mod.rs, src/naming/dto/service_info.rs, src/naming/handler/naming_push_request_handler.rs, src/naming/mod.rs, src/naming/redo/automatic_request/batch_instance_request.rs, src/naming/redo/automatic_request/instance_request.rs, src/naming/redo/automatic_request/subscribe_service_request.rs, src/naming/subscribers/instances_change_event_subscriber.rs, src/naming/subscribers/redo_task_disconnect_event_subscriber.rs
=> Chore: log macro args into string

src/common/remote/grpc/grpc_client.rs, src/common/remote/grpc/handler/client_detection_request_handler.rs, src/naming/mod.rs, src/naming/updater/mod.rs
- remove grpc keep-alive setting
Close #119
=> [ISSUES #119] implement List-Watch

src/common/remote/grpc/grpc_client.rs, src/common/remote/grpc/mod.rs
- set grpc timeout 3s
- set default keep-alive 6 minutes
- set channel query state deadline 10 minutes
Close #126
=> [ISSUES #126] set default timeout

Cargo.toml, src/common/event_bus/mod.rs, src/common/executor/mod.rs, src/common/remote/grpc/bi_channel.rs, src/common/remote/grpc/events/client_init_complete_event.rs, src/common/remote/grpc/events/connection_health_check_event.rs, src/common/remote/grpc/events/disconnect_event.rs, src/common/remote/grpc/events/reconnected_event.rs, src/common/remote/grpc/events/shutdown_event.rs, src/common/remote/grpc/grpc_client.rs, src/common/remote/grpc/handler/client_detection_request_handler.rs, src/common/remote/grpc/mod.rs, src/common/remote/grpc/subscribers/connection_health_check_subscriber.rs, src/common/remote/grpc/subscribers/reconnected_subscriber.rs, src/config/handler.rs, src/config/mod.rs, src/config/worker.rs, src/naming/events/instances_change_event.rs, src/naming/handler/naming_push_request_handler.rs, src/naming/mod.rs, src/naming/redo/automatic_request/batch_instance_request.rs, src/naming/redo/automatic_request/instance_request.rs, src/naming/redo/automatic_request/subscribe_service_request.rs, src/naming/redo/mod.rs, src/naming/subscribers/instances_change_event_subscriber.rs, src/naming/subscribers/redo_task_disconnect_event_subscriber.rs, src/naming/subscribers/redo_task_reconnect_event_subscriber.rs, src/naming/updater/mod.rs
- add tracing span for everywhere
Close #129
=> [ISSUES #129] events isolate

src/api/error.rs, src/common/event_bus/mod.rs, src/common/remote/grpc/bi_channel.rs, src/common/remote/grpc/grpc_client.rs, src/common/remote/grpc/handler/default_handler.rs, src/common/remote/grpc/message/mod.rs, src/common/remote/grpc/mod.rs, src/naming/mod.rs, src/naming/subscribers/redo_task_reconnect_event_subscriber.rs
- optimize payload convert logic
- add ErrResponse error
- add health check task
- optimize bi default handle logic
Close #132
=> [ISSUES #132] enhance health check

CHANGELOG.md, Cargo.toml
- 优化重连机制
---
- Enhance: optimize reconnect logic
=> chore: upgrade version to 0.2.5

Cargo.toml, build.rs, src/common/cache/disk.rs, src/common/cache/mod.rs, src/common/mod.rs
- support data sync to disk
relate #19
=> [ISSUES #19] add common cache component

Cargo.toml, src/common/cache/disk.rs, src/common/cache/mod.rs, src/common/remote/grpc/nacos_grpc_client.rs, src/common/remote/grpc/nacos_grpc_service.rs, src/common/remote/grpc/tonic.rs
- add tower dependency
说明: 使用 tower layer 机制实现类 filter 
note: the filter mechanism implemented by tower layer
=> feat: add filter mechanism

src/common/remote/grpc/mod.rs, src/common/remote/grpc/server_address.rs, src/common/remote/grpc/server_list_service.rs, src/common/remote/grpc/tonic.rs
在发送请求前检测当前`serverAddress`是否可用,如果不可用触发重连,重新选取 `serverAddress`
check `serverAddress` is available before send request ,if the `serverAddress` is not available then trigger reconnect and pick up a new `serverAddress`
=> enhance: check server address is available

.gitignore, CHANGELOG.md, Cargo.toml, README.md, examples/simple_app.rs, src/api/naming.rs, src/api/plugin/auth/auth_by_http.rs, src/common/remote/grpc/tonic.rs, src/lib.rs, src/naming/mod.rs
- merge main, fix conflicts, del deprecated
=> merge: 0.3.x merge main

src/config/handler.rs, src/naming/mod.rs, src/naming/updater/mod.rs
=> Try naming span exlcude service name

README.md
=> doc: Binding for Python

src/api/props.rs
fix #187 
- Fix typos in ClientProps struct
=> [ISSUE #187]Fix typos in ClientProps struct

.github/workflows/ci.yml, examples/simple_app.rs
=> [ISSUE #171]Integration Test with nacos-server

src/api/props.rs
close #192 
- Fix empty check for the server address in method ClientProps#get_server_list is always false
=> [ISSUE #192]Fix empty check for the server address in method ClientProps#get_server_list is always false

Cargo.toml, examples/lazy_app.rs
relate https://github.com/nacos-group/nacos-sdk-rust/issues/222
=> chore: add an example lazy_app

README.md, examples/aliyun_ram_app.rs, src/api/plugin/auth/auth_by_aliyun_ram.rs
* chore: Add example for aliyun ram auth plugin and improve the doc.
* fix: remove invalid test case in auth_by_aliyun_ram
=> Add aliyun ram examples and improve doc
